### ISSUE TITLE
[1.20.1 Fabric] Crash after opening Villager Trade

### ISSUE THREAD

**Issue by pewblaze** [AHilyard/EquipmentCompare#28] opened 2023-07-12 17:48 UTC
Hi, my game crashes after opening a villager trade & hovering over it. Its mentioned in the crash log. 
Im playing on Fabric MC 1.20.1 (0.14.21)
EquipmentCompare-1.20.1-fabric-1.3.6.jar

My logs: 
https://gist.github.com/pewblaze/08a1e3a9863240616d5a16329a95edff

**Comment by TheynT** [comment] 2023-07-13 18:03
I can reproduce this bug as well, with only Equipment Compare 1.3.6 and its dependencies on Quilt 1.20.1:

My log:
https://gist.github.com/TheynT/5d7918fd5c79e15bbf640ea23e8ef1b2

**Comment by Olivka24** [comment] 2023-07-14 18:50
Have the same issue 
The game crashed whilst rendering screen Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1735.method_7681()" because "containerScreen.field_2787" is null

**Comment by ItzNatsu** [comment] 2023-07-15 02:19
Can confirm, this is definitely an issue with version 1.3.6 Fabric.

**Comment by AHilyard** [comment] 2023-07-15 19:09
Thanks for the report, this has been fixed in version 1.3.7.

**Closed by AHilyard** 2023-07-15 19:09 UTC

**Comment by erazare** [comment] 2023-07-16 07:51
you need to apply this fix to the forge branch it has the exact same problem

**Comment by AHilyard** [comment] 2023-07-17 19:37
@erazare Okay, done.  😄

**Comment by erazare** [comment] 2023-07-17 20:05
Ty man!
