### ISSUE TITLE
"inflate data is bad" with EquipmentCompare enabled when joining certain servers

### ISSUE THREAD

**Issue by nickkeane** [AHilyard/EquipmentCompare#9] opened 2022-08-12 07:46 UTC
When connecting to mc.vortexnetwork.net, EquipmentCompare produces the following error:

Internal Exception: io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: inflate data is bad

MC: 1.19.2
Fabric: 0.14.9
EquipmentCompare: 1.3.1

https://pastebin.com/7DsdczAR

**Comment by AHilyard** [comment] 2022-08-12 07:54
Nothing in this log file indicates an error with Equipment Compare.  Could you attach a log that shows the error?

**Comment by AHilyard** [comment] 2022-08-16 05:11
Since this error generally indicates network problems and not issues with client-side mods, I am closing this.  If you can find a reproducible way to show the mod is causing this please reopen.

**Closed by AHilyard** 2022-08-16 05:11 UTC
